# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Eva Tool CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install && npm run build && npm run docs:build
    - name: Generate GitHub Pages v4
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: ./dist
        # Set Git user.name
        git-config-name: eva
        # Set custom commit message
        commit-message: "ci: github action build"
